coach/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

app_name = 'coach'

urlpatterns = [
    path('tip/create/', views.tip_create_update, name='tip_create'),
    path('tip/update/<int:id>/', views.tip_create_update, name='tip_update'),   
    path('tip/list/', views.tip_list, name='tip_list'),
    path('tip/delete/<int:pk>/', views.TipDelete.as_view(), name='tip_delete'),

    path('tag/create/', views.tag_create_update, name='tag_create'),
    path('tag/update/<int:id>/', views.tag_create_update, name='tag_update'),
    path('tag/list/', views.TagList.as_view(), name='tag_list'),
    path('tag/delete/<int:pk>/', views.TagDelete.as_view(), name='tag_delete'),
]

lang/urls.py
from django.urls import include, path
from django.contrib import admin, admindocs
from lang import views as core_views
from django.conf.urls.i18n import i18n_patterns
from main import views as main_views
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns (
    path('main/', include('main.urls')),
    path('grammar/', include('grammar.urls')),
    path('coach/', include('coach.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),    
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('new_login/', core_views.new_login, name='new_login'),
    path('accounts/logout/', core_views.logout_view, name='logout_view'),
    path('', splash_view, name='splash'),
    path('no_cookies/', no_cookies, name='no_cookies'),
)
"""
django.contrib.auth.urls creates:
    accounts/ login/ [name='login']
    accounts/ logout/ [name='logout']
    accounts/ password_change/ [name='password_change']
    accounts/ password_change/done/ [name='password_change_done']
    accounts/ password_reset/ [name='password_reset']
    accounts/ password_reset/done/ [name='password_reset_done']
    accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
    accounts/ reset/done/ [name='password_reset_complete']
"""    

coach/models/tiptag.py
from django.db import models

class TipTag(models.Model):
    tip = models.ForeignKey('Tip', on_delete=models.CASCADE)
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE)
    relationship = models.BooleanField(default = True, db_index=True, help_text="True if Tag condition required, False if Tag condition rejected/must be false") 

coach/forms.py
from django import forms
from .models import Tip
from main.models import Language
from django.shortcuts import get_object_or_404
import logging
from tinymce.widgets import TinyMCE
from main.views import get_sp_or_redirect 
from coach.models import Tag, TipTag
from main.models import Sentence, Language

    # auto populate native_language, author, parent, 
#    tags # dropdown, categories (source, sitution, level) each leading to a separate dropdown with a control-select... also give an any field...
        # AJAX auto-complete...    Situation:I
        # checkboxes: of upto 10 possible 10 tags 

class FollowUpHomeworkForm(forms.Form):
    pass
    # presents each tip_homework title, then followup question, and a expand toggle to read full original description
    # presents each tip_advice title, then choice to bookmark, reject

class TagForm(forms.Form):
    title = forms.CharField(required=True, label='Title', widget=forms.TextInput(attrs={'autofocus': 'autofocus'}))
    native_language = forms.IntegerField(widget=forms.HiddenInput(),required=True)
    parent = forms.IntegerField(required=False,widget=forms.HiddenInput())
    id = forms.IntegerField(widget=forms.HiddenInput(),required=False)

    def save(self,request):
        log = logging.getLogger(__name__)
        data = self.cleaned_data

        if self.initial['id'] is None: # creating
            # create sub objects
            sentence_parent = None
            if self.initial['parent'] is not None:
                sentence_parent = Tag.objects.filter(id=self.initial['parent']).first()
                
            title_sentence = Sentence.objects.create(
                    text = data['title'],
                    language = Language.objects.get(id=self.initial['native_language']),
                    parent = sentence_parent,
                    author = request.user
                )
            # create main object
            tag = Tag.objects.create(title = title_sentence,
                                     parent = self.initial['parent'],
                                     author = request.user,
                                     )
            log.info("User " + request.user.username + " created tag "+ str(data['title']))
        else: # updating existing tag
            tag = get_object_or_404(Tag, id=self.initial['id'])
            if self.has_changed():                
                tag.title.text = data['title']
                tag.title.save()
                tag.save()
                log.info("User " + request.user.username + " updated tag " + str(data['title']))

class TipForm(forms.Form):
    title = forms.CharField(required=True, help_text="Summary title for the advice", label='Title', widget=forms.TextInput(attrs={'autofocus': 'autofocus'}))
    text = forms.CharField(required=False, widget=TinyMCE(mce_attrs={'cols': 20, 'required': False}), help_text="Advice for the student", label='Coaching advice')
    homework_text = forms.CharField(required=False, widget=TinyMCE(mce_attrs={'cols': 20, 'required': False}), help_text="Homework exercise for the student", label='Homework task')
    id = forms.IntegerField(widget=forms.HiddenInput(),required=False)
    parent = forms.IntegerField(widget=forms.HiddenInput(),required=False)
    language_specific = forms.BooleanField(required=False, help_text="Is this tip specific to only certain languages?") # booleanfields always need required=False else if left unchecked they are considered not filled in
    target_language = forms.IntegerField(widget=forms.HiddenInput(),required=True)
    native_language = forms.IntegerField(widget=forms.HiddenInput(),required=True)
    stage = forms.IntegerField(required=True, help_text="Earliest stage this tip will be available")

    def __init__(self, *args, **kwargs):         
        super(TipForm, self).__init__(*args, **kwargs)         
        self.fields['tags_INC'] = forms.MultipleChoiceField(choices=self.initial['tag_choices'],
                                                         label = 'Tags',
                                                         initial = self.initial['selected_tags_INC'], 
                                                         required=False,   
                                                         widget=forms.CheckboxSelectMultiple,                                                                 
                                                         )
        self.fields['tags_EXC'] = forms.MultipleChoiceField(choices=self.initial['tag_choices'],
                                                         label = 'Tags',
                                                         initial = self.initial['selected_tags_EXC'], 
                                                         required=False,   
                                                         widget=forms.CheckboxSelectMultiple,                                                                 
                                                         )

    def clean(self):
        cleaned_data = super().clean()
        # either text or homework_text must be filled in
        if len(cleaned_data.get("text")) == 0 and len(cleaned_data.get("homework_text")) == 0:
            self.add_error('text', 'This tip must contain at least Coaching advice or a Homework task, but both cannot be blank.')  
        
    def save(self,request):
        log = logging.getLogger(__name__)
        data = self.cleaned_data

        if self.initial['id'] is None: # creating
            # create sub-objects
            # create main object
            tip = Tip.objects.create(title = data['title'],
                                     text = data['text'],
                                     homework_text = data['homework_text'],
                                     native_language = Language.objects.get(id=self.initial['native_language']),
                                     parent = self.initial['parent'],
                                     author = request.user,
                                     language_specific = data['language_specific'],
                                     stage = data['stage'],
                                     )
            log.info("User " + request.user.username + " created tip "+ str(data['title']))
        else: # updating existing tip
            tip = get_object_or_404(Tip, id=self.initial['id'])
            if self.has_changed():
                tip.title = data['title']
                tip.text = data['text']
                tip.homework_text = data['homework_text']
                # native_language : doesn't change
                # parent : doesn't change
                # author : doesn't change, stays as original
                tip.language_specific = data['language_specific']
                tip.stage = data['stage']
                tip.save()
                log.info("User " + request.user.username + " updated tip " + str(data['title']))

        # add tags
        tip.tags.clear()
        lang_tag = Tag.objects.lang_tag(self.initial['target_language'])
        lang_tag_added = False
        for tag_id in data['tags_INC']:
            tag = Tag.objects.get(id=tag_id)
            if tag == lang_tag:
                lang_tag_added = True
            TipTag.objects.create(tip=tip, tag=tag, relationship=True)
        # To prevent errors due to a tag being ticked in both lists, we first remove all 
        # tags_INC elements from tags_EXC
        modified_tags_EXC = [item for item in data['tags_EXC'] if item not in data['tags_INC']]
        for tag_id in modified_tags_EXC:
            tag = Tag.objects.get(id=tag_id)
            if tag == lang_tag:
                lang_tag_added = True
            TipTag.objects.create(tip=tip, tag=tag, relationship=False)
                     
        if data['language_specific'] == True and not lang_tag_added:
            lang_tag = Tag.objects.lang_tag(self.initial['target_language'])
            TipTag.objects.create(tip=tip, tag=lang_tag,relationship=True)
        elif data['language_specific'] == False and not lang_tag_added:
            # If later a user de-selected language_specific, we can let the language_tag remain in whatever state
            pass                

coach/views/add_content.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.template import Context
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from ..models import * 
from django.contrib import messages
from common import css, template_filters
import logging
from django.contrib.auth.decorators import permission_required
from main.views import get_sp_or_redirect
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.contrib.auth.mixins import PermissionRequiredMixin
from coach.forms import TipForm, TagForm

@permission_required('main.admin')
def integrity_check(request):
    log = logging.getLogger(__name__)

class TipDelete(PermissionRequiredMixin,DeleteView):
    permission_required = 'coach.delete_tip'
    model = Tip
    template_name = 'main/model_confirm_delete.html'
    success_url = reverse_lazy('coach:tip_list')

@permission_required(['coach.add_tip'],raise_exception=True)
def tip_list(request):
    sp,request = get_sp_or_redirect(request)
    if not sp:
        return redirect('main:select_course')

    tip_list = []
    for tip in Tip.objects.filter(native_language=sp.native_language).order_by('stage'):
        tags_REQUIRED = []
        tags_REJECTED = []
        for tag in tip.tags.filter(tiptag__relationship=True):
            tags_REQUIRED.append(tag.title_in(sp.native_language))
        for tag in tip.tags.filter(tiptag__relationship=False):
            tags_REJECTED.append(tag.title_in(sp.native_language))
            
        tip_list.append({
            'id': tip.id,
            'title': tip.title,
            'stage': tip.stage,
            'exposures': tip.exposures,
            'tags_REQUIRED': tags_REQUIRED,
            'tags_REJECTED': tags_REJECTED,
            'uptake': int(tip.uptake()*100),
            })
        
    context = {
        'tip_list': tip_list,
        }
    return render(request, 'coach/tip_list.html', context)

@permission_required(['coach.add_tip','coach.change_tip'],raise_exception=True)
def tip_create_update(request, id=None):
    sp,request = get_sp_or_redirect(request)
    if not sp:
        return redirect('main:select_course')
    
    available_tags = Tag.objects.tags_in(sp.native_language)
    initial = {
            # fields that appear as Form Fields
        'native_language':sp.native_language.id,        
        'tag_choices': Tag.objects.tags_in(sp.native_language),
        'selected_tags_INC': None,
        'selected_tags_EXC': None,
        'language_specific': False,
        'stage': '',
        'title': '',
        'id': id,
        'parent': None,
        'target_language': sp.course.target_language.id,
        }
    # context is info not in the form fields but used to render the template
    context = {
        'id': None if id == None else int(id),
#        'target_language': sp.course.target_language.id,
        }
    if id is not None: # update mode
        context['title'] = 'Update Coaching Tip'
        tip = get_object_or_404(Tip, id=id)
        selected_tags_INC = set()
        selected_tags_EXC = set()
        for tag in tip.tags.filter(tiptag__relationship=True):
            selected_tags_INC.add(tag.id)
        for tag in tip.tags.filter(tiptag__relationship=False):
            selected_tags_EXC.add(tag.id)       
        initial.update({
            'id': id,
            'title': tip.title,
            'text': tip.text,
            'homework_text': tip.homework_text,
            'parent': tip.parent,
            'selected_tags_INC': list(selected_tags_INC),
            'selected_tags_EXC': list(selected_tags_EXC),
            'language_specific': tip.language_specific,
            'stage': tip.stage,
            })
    else: # create mode
        context['title'] = 'Create a new Coaching Tip'
    if request.method == 'POST': # saving
        form = TipForm (request.POST, initial=initial)
        if form.is_valid():
            form.save(request)
            messages.add_message(request, messages.SUCCESS, 'Tip successfully saved')
            return redirect('coach:tip_list')
    else: # rendering initial form
        form = TipForm (None, initial=initial)
    context['form'] = form
    return render(request, 'coach/tip_create_update.html', context)

class TagDelete(PermissionRequiredMixin,DeleteView):
    permission_required = 'coach.delete_tag'
    model = Tag
    template_name = 'main/model_confirm_delete.html'
    success_url = reverse_lazy('coach:tag_list')

    def get_context_data(self, **kwargs):
        # This method allows us to add extra context information to the generic view
        context = super().get_context_data(**kwargs)
        context.update({
                'model_name':'Tag',
            })
        return context    



@permission_required(['coach.add_tag','coach.change_tag'],raise_exception=True)
def tag_create_update(request, id=None):
    sp,request = get_sp_or_redirect(request)
    if not sp:
        return redirect('main:select_course')
    
    initial = {
            # fields that appear as Form Fields
        'id':id,
        'title':None,
        'native_language':sp.native_language.id,     
        'parent':None,   
        }
    # context is info not in the form fields but used to render the template
    context = {
        }
    if id is not None: # update mode
        tag = get_object_or_404(Tag, id=id)
        initial.update({
            'id': id,
            'title': tag.title,
            'parent': tag.parent,
            })
        context.update({
            'id': id,
            'title':'Update Tag',
            })
    else: # create mode
        context['title'] = 'Create a new Tag'
    if request.method == 'POST': # saving
        form = TagForm (request.POST, initial=initial)
        if form.is_valid():
            form.save(request)
            messages.add_message(request, messages.SUCCESS, 'Tag successfully saved')
            return redirect('coach:tag_list')
    else: # rendering initial form
        form = TagForm (None, initial=initial)
    context['form'] = form
    return render(request, 'coach/tag_create_update.html', context)

class TagList(PermissionRequiredMixin,ListView):    
    permission_required = 'coach.content_creator'
    model = Tag
    template_name = 'main/model_list.html'

    def get_context_data(self, **kwargs):
        # This method allows us to add extra context information to the generic view
        context = super().get_context_data(**kwargs)
        context.update({
                'update_url':'coach:tag_update',
                'delete_url':'coach:tag_delete',
                'create_url':'coach:tag_create',
                'model_name':'Tag'
            })
        return context    

coach/templates/coach/exercises_subtable.html
   	{% for exercise in selected_exercises %}
        <div class="card bg-light" style="background-color:lightblue">            
            <div class="card-body">
                <h3 class="card-title">{{ exercise.title }}</h3>
                <div class="card-text">
                    {{ exercise.homework_text|safe }}
                </div>
            </div>
        </div>
        <br>
   {% empty %}
   <p>No exercises found for today.</p>
   {% endfor %}

coach/templates/coach/tag_create_update.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <p>
        <a href="{% url 'coach:tag_list'%}"> <button class="btn btn-primary" value="">Tag list</button></a>
	    {% if 'Update' in title  %}
	        <a href="{% url 'coach:tag_delete' id %}"> <button class="btn btn-danger" value="">Delete tag</button></a>
	    {% endif %}
    </p>
    <form method='POST' action=''>{% csrf_token %}
        {% include "main/form_header_snippet.html" %}           
        <div class="row">
            <div class="col-md-12">
                {% include "main/field_snippet.html" with field=form.title %}
            </div>
        </div>
        <br>
        <input class="btn btn-primary" type="submit" value="Save" />        
    </form>

{% endblock %}


{% block javascript %}
{% endblock %}

coach/templates/coach/tip_create_update.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <p>
        <a href="{% url 'coach:tip_list'%}"> <button class="btn btn-primary" value="">Return to Tip list</button></a>
	    {% if 'Update' in title  %}
	        <a href="{% url 'coach:tip_delete' id %}"> <button class="btn btn-danger" value="">Delete tip</button></a>
	    {% endif %}
    </p>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    {{field.label}}: {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <form method='POST' action=''>{% csrf_token %}
        {% include "main/form_header_snippet.html" %}           
        <div class="row">
            <div class="col-md-6">
                {% include "main/field_snippet.html" with field=form.title %}
            </div>
            <div class="col-md-3">
                {% include "main/field_snippet.html" with field=form.language_specific %}
            </div>
            <div class="col-md-3">
                {% include "main/field_snippet.html" with field=form.stage %}
            </div>                  
        </div>
        <h2>{{form.text.label}}</h2>
        <small class="form-text text-muted">{{ form.text.help_text }}</small>
        <div class="row">
            <div class="col-md-12">
                {{ form.text }}
            </div>
        </div>
        <h2>{{form.homework_text.label}}</h2>      
        <small class="form-text text-muted">{{ form.homework_text.help_text }}</small>
        <div class="row">
            <div class="col-md-12">
                {{ form.homework_text }}
            </div>
        </div>      


        <div class="card card-body bg-light">
            <div class="container">
		        <div class="row">
		            <div class="col-md-6">
		                <h3>Tags that must be true</h3>
		                {{ form.tags_INC }}
		            </div>
		            <div class="col-md-6">
		                <h3>Tags that must be false</h3>
		                {{ form.tags_EXC }}
		            </div>
		        </div>

                {% for category in all_categories %}
                    <span class="category-checkbox">
                        <button type="button" 
                        
                            {% if category.id in selected_categories %}
                                class="btn btn-success" id="category_button_{{ category }}">{{ category.title }}</button>
                                <input type="checkbox" class="hidden" id="category_checkbox_{{ category.id }}" name = "selected_categories[]" value="{{ category.id }}" checked>
                            {% else %}
                                class="btn btn-default" id="category_button_{{ category.id }}">{{ category.title }}</button>
                                <input type="checkbox" class="hidden" id="category_checkbox_{{ category.id }}" name = "selected_categories[]" value="{{ category.id }}">                         
                            {% endif %}                     
                    </span>
                {% empty %}
                {% endfor %}
            </div>
        </div>  
    
        {% comment %} list out tags as hidden elements, displayed on click of appropriate category {% endcomment %}
        <div class="card card-body bg-light">
            {% for category in all_categories %}
            <div id="category_tag{{ category.id }}" 
                {% if category.id in selected_categories %}
                    >
                {% else %}
                    style="display: none;">
                {% endif %}
                {% for field in form.visible_fields %}
                    {% if category.name in field.name %}
                        {{ field.label_tag }}
                        render_field field class="form-control"
                    {% endif %}
                {% empty %}
                    <a href="{% url 'coach:tag_create' %}" class="list-group-item">No tags registered for this category - click here to create</a>
                {% endfor %}
            </div>
            {% endfor %}            
            <input class="btn btn-primary" type="submit" value="Save" />        
        </div>
        <br>
    </form>
    <a href="{% url 'coach:tag_create' %}"><button class="btn btn-success" value="">Create a new tag</button></a>   
{% endblock %}


{% block javascript %}

    // reveal category's tag and highlight button
    $("body").click(function(e){
        if (e.target.id.startsWith("category_button_")) {
            var but_id_num = e.target.id.replace("category_button_","")
            var checkbox_id = "#category_checkbox_" + but_id_num; 
            var gram_id = "#category_tag" + but_id_num;
            if ($(e.target).attr('class') == 'btn btn-success') {
                $(e.target).removeClass("btn btn-success").addClass("btn btn-default");
                $(gram_id).hide();
            } else if ($(e.target).attr('class') == 'btn btn-default') {
                $(e.target).removeClass("btn btn-default").addClass("btn btn-success");
                $(gram_id).show();
            };
            $(checkbox_id).prop('checked', !$(checkbox_id).is(':checked')) // inverse check
        };
    });
    
{% endblock %}

coach/templates/coach/tip_list.html
{% extends 'base.html' %}

{% block title %}Tip List{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <th></th>
            <th>Title</th>
            <th>Stage</th>
            <th>Uptake/Exposures</th>
            <th></th>
        </thead>
        <tbody>
	    	{% for entry in tip_list %}
		       <tr>
		           <td><a href="{% url 'coach:tip_update' entry.id %}"><button type="button" class="btn btn-primary">Update</button></a></td>
	               <td>
	                   <strong>{{ entry.title }}</strong><br>	                   
	                   <p>
		                   {% if entry.tags_REQUIRED %}
			                   {% for req_tag in entry.tags_REQUIRED %}
			                       <span class="bg-success">{{ req_tag }}</span>
		                       {% endfor %}
	                       {% endif %}
	                       {% if entry.tags_REJECTED %}
	                           {% for rej_tag in entry.tags_REJECTED %}
	                               <span class="bg-danger">{{ rej_tag }}</span> 
	                           {% endfor %}
	                       {% endif %}
                       </p>
                   </td>
	               <td>{{ entry.stage }}</td>
	               <td>{{ entry.uptake }}% / {{ entry.exposures }}</td>
	               <td><a href="{% url 'coach:tip_delete' entry.id %}"><button type="button" class="btn btn-danger"><i class="fas fa-trash" aria-hidden="true"></i></button></a></td>
	          </tr>
		   {% empty %}
		   <tr><td>No tips found.</td></tr>
		   {% endfor %}
        </tbody>
   </table>
    <a href="{% url 'coach:tip_create' %}"><button type="button" class="btn btn-success">Create a new tip</button></a>
    <a href="{% url 'coach:tag_list'%}"> <button class="btn btn-primary" value="">Tag list</button></a>
    
{% endblock %}

coach/templates/coach/tips_subtable.html
   	{% for tip in selected_tips %}
        <div class="card bg-light" style="background-color:lightblue">            
            <div class="card-body">
                <h3 class="card-title">{{ tip.title }}</h3>
                <div class="card-text">
                    {{ tip.text|safe }}
                </div>
            </div>
        </div>
        <br>
   {% empty %}
   <p>No tips found for today.</p>
   {% endfor %}

coach/templates/coach/view_selected_exercises.html
{% extends 'base.html' %}

{% block title %}Homework exercises{% endblock %}

{% block content %}
   {% include 'coach/exercises_subtable.html' %}
   {% include 'main/continue_button_form_snippet.html' %}
{% endblock %}

coach/templates/coach/view_selected_tips.html
{% extends 'base.html' %}

{% block title %}Coaching Advice{% endblock %}

{% block content %}
   {% include 'coach/tips_subtable.html' %}
   {% include 'main/continue_button_form_snippet.html' %}
{% endblock %}