grammar/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

app_name = 'grammar'

urlpatterns = [
# add_content views
    path('gramconcept/', views.GramConceptList.as_view(), name='gramconcept_list'),
    path('gramconcept/create/', views.GramConceptCreate.as_view(), name='gramconcept_create'),
    path('gramconcept/update/<int:pk>/', views.GramConceptUpdate.as_view(), name='gramconcept_update'),
    path('gramconcept/delete/<int:pk>/', views.GramConceptDelete.as_view(), name='gramconcept_delete'),
    
    path('grammar/dashboard/', views.create_dashboard, name='create_dashboard'),
    path('grammar/update/<int:pk>/', views.gram_update, name='gram_update'),
    path('grammar/create/', views.gram_update, name='gram_create'),    
    path('grammar/delete/<int:pk>/', views.GrammarDelete.as_view(), name='grammar_delete'),
    path('grammar/restage/<int:pk>/', views.grammar_restage, name='grammar_restage'),
        
    path('question/new_from_grammar/<int:grammar_id>/', views.update_question, name='new_question_for_grammar'),
    path('question/new_from_sentence/<int:sentence_id>/', views.update_question, name='new_question_from_sentence'),
    path('question/new/', views.update_question, name='new_question'),
    path('question/update/<int:question_id>/', views.update_question, name='update_question'),    
    path('question/delete/<int:pk>/', views.QuestionDelete.as_view(), name='question_delete'),
    path('question/list/example_questions/<int:grammar_id>/', views.example_questions, name='example_questions'),

    path('question/ratify/', views.ratify_questions, name='ratify_questions'),
    path('question/view_ratifications/', views.view_ratifications, name='view_ratifications'),
    path('question/apply_ratification_update/<int:pk>/', views.apply_ratification_update, name='apply_ratification_update'),
    
    


# assess views    
    path('assess/initial/', views.initial_grammar_test, name='initial_grammar_test'),
    path('assess/run_initial/', views.run_initial_placement, name='run_initial_placement'),
    path('assess/weekly/schedule_qs/', views.weekly_assessment_schedule_qs, name='weekly_assessment_schedule_qs'),
    path('assess/weekly/ask_qs/', views.weekly_assessment_ask_qs, name='weekly_assessment_ask_qs'),
    path('assess/question_score/', views.question_score, name='question_score'),
    path('ajax/submit_answer/', views.ajax_submit_answer, name='ajax_submit_answer'),
    path('report/', views.weekly_assessment_report, name='weekly_assessment_report'),
]

lang/urls.py
from django.urls import include, path
from django.contrib import admin, admindocs
from lang import views as core_views
from django.conf.urls.i18n import i18n_patterns
from main import views as main_views
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns (
    path('main/', include('main.urls')),
    path('grammar/', include('grammar.urls')),
    path('coach/', include('coach.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),    
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('new_login/', core_views.new_login, name='new_login'),
    path('accounts/logout/', core_views.logout_view, name='logout_view'),
    path('', splash_view, name='splash'),
    path('no_cookies/', no_cookies, name='no_cookies'),
)
"""
django.contrib.auth.urls creates:
    accounts/ login/ [name='login']
    accounts/ logout/ [name='logout']
    accounts/ password_change/ [name='password_change']
    accounts/ password_change/done/ [name='password_change_done']
    accounts/ password_reset/ [name='password_reset']
    accounts/ password_reset/done/ [name='password_reset_done']
    accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
    accounts/ reset/done/ [name='password_reset_complete']
"""    

main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'

urlpatterns = [
    path('test/', views.test, name='test'), 
    path('integrity_check/', views.integrity_check, name='integrity_check'), # run some sort of test - for debugging
    path('', views.switchboard, name='switchboard'),
    path('switchboard/<mode>/', views.switchboard, name='switchboard'),
    path('review_summary/', views.review_summary, name='review_summary'),
                  
    path('select_course/', views.select_course, name='select_course'),
    path('signup_course/', views.signup_course, name='signup_course'),
    path('reset_all_student_progress/', views.reset_all, name='reset_all'),
    path('add_stage/', views.add_stage, name='add_stage'),
    path('getting_started/', views.getting_started, name='getting_started'),
    path('profile/', views.profile_user, name='profile_user'),
    path('register_new_user/', views.register_new_user, name='register_new_user'),
    
]

coach/models/tag.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Language, Sentence
from common.MixinClasses import TranslatableMixin
import logging


class TagManager(models.Manager):
    def tags_in(self,language):
        available_tags=[]
        for tag in Tag.objects.all():
            available_tags.append((tag.id,tag.title_in(language)))
        return available_tags
    
    def lang_tag(self,language_id):
        # returns name of tag, first creates one if it does not yet exist
        English = Language.objects.English()
        language = Language.objects.get(id=language_id)
        tag_title="Lang:{}".format(language.title_in_English())        
        lang_tag_q = Tag.objects.filter(title__text=tag_title)
        if lang_tag_q.exists():
            lang_tag = lang_tag_q.first()
        else:
            # if tag does not yet exist, create
            lang_tag_title = Sentence.objects.create(
                text=tag_title,
                language=English,
                author=None,
                )
            lang_tag = Tag.objects.create(
                title=lang_tag_title,
                author=None,
                ) 
        return lang_tag
    
class Tag(TranslatableMixin, models.Model):
    """
    """
    title = models.ForeignKey('main.Sentence', on_delete=models.CASCADE, related_name='TagTitles')
    parent = models.ForeignKey('Tag',null=True,blank=True, on_delete=models.SET_NULL)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    objects = TagManager()

    def save(self, *args, **kwargs):
        super(Tag, self).save(*args, **kwargs)
    
    class Meta:
        ordering = ['-created']
        permissions = (
            ("content_creator", "Can create,read,update,delete"),
        )
        

coach/models/tip.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.db import models
from django.contrib.auth.models import User
import logging
from main.models import Language
from coach.models import TipEncounter
from tinymce import HTMLField

class TipManager(models.Manager):
    def select(self, sp, total_point=12):
        """
            Returns a list of Tips selected for viewing by the user.
            total_points should be set in the range 10-26 
        """
        encountered_tip_ids = TipEncounter.objects.filter(sp=sp).values_list('tip',flat=True)
        if encountered_tip_ids is None:
            encountered_tip_ids = []
        candidate_tips = Tip.objects.exclude(id__in=encountered_tip_ids).filter(stage__lte=sp.stage.position).order_by('stage')
        tiny_count = 0
        medium_count = 0
        large_count = 0
        selected = []
        
        
        # pick tips
        remaining_points = total_point
        for choice in candidate_tips:
            # check if tags match user profile
            # check size fits
            if choice.size <= remaining_points:
                if choice.size == Tip.TINY:
                    if tiny_count > 2:
                        continue
                    else:
                        tiny_count += 1
                        
                if choice.size == Tip.MEDIUM:
                    if medium_count > 1:
                        continue
                    else:
                        medium_count += 1
                if choice.size == Tip.LARGE:
                    if large_count > 0:
                        continue
                    else:
                        large_count += 1
                remaining_points -= choice.size                        
                selected.append(choice)
                TipEncounter.objects.create(tip=choice,sp=sp)
                remaining_points -= choice.size
        return selected

class Tip(models.Model):
    """
    """

    TINY = 2
    MEDIUM = 5
    LARGE = 10
    SIZE_CHOICES = ((TINY, 'Tiny'), (MEDIUM, 'Medium'), (LARGE, 'Large'))   

    title = models.CharField(max_length=80)
    text = HTMLField(blank=True,null=True)
    homework_text = HTMLField(blank=True,null=True)

    # Unlike other models, tips have native_language and parent recorded as language translations often involve specialized alteration
    native_language = models.ForeignKey('main.Language', on_delete=models.CASCADE)
    parent = models.ForeignKey('Tip', null=True, blank=True, on_delete=models.SET_NULL, db_index=True, help_text="If this tip is a translation of another tip")
    tags = models.ManyToManyField('Tag', through='TipTag')
    # USE TAGS AND BAYSIAN... target_language = models.ManyToManyField('main.Language', blank=True, help_text="Null if this tip is suitable to multiple languages")
    bookmarks = models.IntegerField(default=0, help_text="Number of people who bookmarked this tip")
    exposures = models.IntegerField(default=0, help_text="Number of people who were presented this tip")
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    language_specific = models.BooleanField(default=False)
    stage = models.IntegerField(help_text="Earliest stage this tip will be available")
    size = models.IntegerField(choices=SIZE_CHOICES, db_index=True, default=MEDIUM, help_text="How much work and reading this tip requires")   
    objects = TipManager()

    def uptake(self):
        if self.exposures > 0:
            return self.bookmarks/self.exposures
        else:
            return 0

    def save(self, *args, **kwargs):
        # work out size of tip
        # If has homework, automatically LARGE.
        # If text section of text has a len>100 size = MEDIUM
        # If text < 100, size = TINY
        if self.homework_text is not None:
            if len(self.homework_text) > 20:
                self.size = self.LARGE
        elif self.text is not None: 
            if len(self.text) > 100:
                self.size = self.MEDIUM
        else:
            self.size = self.TINY
        super(Tip, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.title)
    
    class Meta:
        ordering = ['-created']

coach/models/tipencounter.py
from django.db import models
import logging
    
class TipEncounter(models.Model):
    """
    Tracks which users have viewed which tips and whether the user bookmarked the tip
    """

    CURRENT = 'C' # Currently being viewed and actioned
    BOOKMARKED = 'B' # Selected by user to save/archive/bookmark
    DELAYED = 'D' # Felt it was too advanced, wanted to come back later
    REJECTED = 'R' # Rejected
    PREVIOUSLY = 'P' # Was already being implemented prior to viewing the tip (i.e. "I already do this!") 
    STATUS_CHOICES = ((CURRENT, 'Current'), (BOOKMARKED, 'Bookmarked'), (DELAYED, 'Delayed'), (REJECTED, 'Rejected'), (PREVIOUSLY, 'Previously implemented'))   
    
    tip = models.ForeignKey('Tip', on_delete=models.CASCADE)
    sp = models.ForeignKey('main.StudentProgress', null=True, on_delete=models.SET_NULL)
    date = models.DateField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, db_index=True, default=CURRENT, help_text="How the user has responded to the proffered tip") 
    

coach/models/tiptag.py
from django.db import models

class TipTag(models.Model):
    tip = models.ForeignKey('Tip', on_delete=models.CASCADE)
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE)
    relationship = models.BooleanField(default = True, db_index=True, help_text="True if Tag condition required, False if Tag condition rejected/must be false") 

grammar/models/attempt.py
from django.db import models
from django.contrib.auth.models import User
from .entry import Entry
import logging

class AttemptManager(models.Manager):
    def q_type_of(self, target_type, results_desired=1, language=None):
        # returns questions with the greatest percentage of target_type self_assessments.
        
        q_scores = {} # dictionary to record highest scoring questions
#        Qs = Attempt.objects.order_by().values('question').distinct()    # could also do this operation on question_progress table, but attempt table keeps records even for deleted users
        for q in Qs:
            # skip Qs of another language
            if (language is not None):
                if q.question.grammar.stage.target_language != language:
                    continue # skip the rest of this iteration
            
            # find all attempts for this question
            wrong_count = 0
            As = Attempt.objects.filter(question = q)    
            for a in As:
                # iterate through each attempt and count wrongs
                if a.self_assesment == target_type:
                    wrong_count += 1
            q_scores[q] = wrong_count/len(As)
        
        
        results = []
        return_count = min(results_desired,len(q_scores))
        for i in range(return_count):
            r = max(q_scores, key=q_scores.get)
            results.append(r)
            del(q_scores[r])
        return results

    def hardest_questions(self, results_desired=1, language=None):
        return self.q_type_of(Attempt.WRONG,language,results_desired)
    
    def most_reported_questions(self, results_desired=1, language=None):
        return self.q_type_of(Attempt.REPORT,language,results_desired)

class Attempt(models.Model):
    """
    Stores student attempts and results at a particular :model:`grammar.Question` 
    Points to an :model:`grammar.entry` related to what they typed, records the user, 
    ELO and variance at the time    
    """

    CORRECT = Entry.CORRECT
    WRONG = Entry.WRONG
    REPORT = Entry.REPORT
    A_TYPE_CHOICES = ((CORRECT, 'Right'), (WRONG, 'Wrong'), (REPORT, 'There is a problem with the question'))   

    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    raw_entry = models.CharField(max_length=200, help_text="Original text entered by user")
    entry = models.ForeignKey('Entry', on_delete=models.CASCADE, help_text="Entry associated with this and other similar attempts")
    assessment = models.CharField(max_length=1,choices=A_TYPE_CHOICES, db_index=True, help_text="How the attempt was automatically assessed or self-assessed by the user")   
    feedback = models.CharField(max_length=200, help_text="Reported feedback from the user concerning the question",blank=True)
    score = models.FloatField(null=True, blank=True, help_text="score of the user when this attempt was made - only recorded if variance below a certain threshold, otherwise null")    
    variance = models.FloatField(null=True, help_text="variance of the user when this attempt was made - only recorded if variance below a certain threshold, otherwise null")
    created = models.DateTimeField(auto_now_add=True)
    #objects = AttemptManager()

    def save(self, *args, **kwargs):
        super(Attempt, self).save(*args, **kwargs)

    def __str__(self):
        return str([self.entry])
    
    class Meta:
        ordering = ['-created']

main/models/data.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from common import css
import logging
from datetime import date

class DataManager(models.Manager):
    def getval(self,key):
        # Returns None if entry not found
        # Cached data records are only good for 7 days, then they are deleted 
        try:
            record = Data.objects.get(key=key)
            if (date.today() - record.date).days > 7:
                record.delete()
                return None
            else:
                return css.literal(record.value)
        except:
            return None
    
    def create_or_update(self,key,value):
        try:
            record = Data.objects.get(key=key)
            record.value = value
            record.save()
        except:
            record = Data.objects.create(key=key,value=value)

class Data(models.Model):
    """
        Stores key/value pairs for the system, useful for caching data. A flexible storage system.
    """
    key = models.CharField(max_length=90, unique=True)
    value = models.CharField(null=True, max_length=200,blank=True)
    date = models.DateField(auto_now=True)
    objects = DataManager()

    def save(self, *args, **kwargs):
        super(Data, self).save(*args, **kwargs)
        log = logging.getLogger(__name__)
        log.info("Model Data Instance saved:"+str(self))

    def __str__(self):
        return  str([self.key, self.value])

    class Meta:
        ordering = ['date']

grammar/templates/grammar/create_dashboard.html
{% extends 'base.html' %}

{% block title %}Grammars{% endblock %}

{% block content %}
<div class="container">
	<p>
		<a href="{% url 'grammar:gram_create'%}"> <button class="btn btn-primary" value="">Add new grammar</button></a>
		<a href="{% url 'main:add_stage'%}"> <button class="btn btn-primary" value="">Add additional stage</button></a>
		{% if perms.grammar.super_creator %}
		  <a href="{% url 'grammar:gramconcept_list'%}"> <button class="btn btn-default" value="">View Grammar Concepts</button></a>
		{% endif %}
	</p>
	{% include "grammar/gram_list_snippet.html" %}
</div>
{% endblock %}

grammar/templates/grammar/example_questions.html
{% extends 'base.html' %}

{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js">
    </script>
{% endblock %}


{% block title %}Example questions for<br>{{grammar_title}}{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
			<th>Question</th>
			<th>Answer</th>
			<th>Grammar
                 <span style="color:Tomato" data-html="true" data-trigger="hover" data-toggle="tooltip" title="A green tick indicates this question tests {{grammar_title}} grammar. Otherwise 
                 the sentence is considered to have a harder grammar as indicated and will not be used to test this grammar.">
                     <i class="fas fa-question-circle fa-lg"></i>
                 </span>   			
			</th>	
			<th></th>
		</tr>
	</thead>
	<tbody>
	{% for key,value in output.items %}
		{% if value.title %}
			<tr style="background: #eeeeee;">
				<th></th>
				<th></th>
				<th></th>
				<th></th>				
			</tr>
		{% else %}
				<tr>
					{% if value.question_id is not None %}
						<td>{{ value.front }}</td>
						<td>{{ value.back }}</td>
						<td>
						{% if value.belong == True %}<button type="button" class="btn btn-success"><i class="fas fa-check-circle" aria-hidden="true"></i></button>
						{% else %}
						<button type="button" class="btn btn-default">{{ value.grammar_title }}</button>
						{% endif %}
						</td>
						<td>
							<a href="{% url 'grammar:question_delete' value.question_id %}"><button type="button" class="btn btn-danger"><i class="fas fa-trash" aria-hidden="true"></i></button></a>
							<a href="{% url 'grammar:update_question' value.question_id %}"><button type="button" class="btn btn-primary">Edit</button></a>							
						</td>
					{% else %}
							<td>{{ value.front }}</td>
							<td>
								<a href="{% url 'grammar:new_question_from_sentence' value.sentence_id %}"><button type="button" class="btn btn-default">Create a matching translation</button></a>
							</td>
							<td></td>
							<td>
							</td>
							<td></td>
					{% endif %}
		  		</tr>

		{% endif %}
		{% if value.sentence_id is None %}
		{% else %}
		</a></tr> 
		{% endif %}
	{% endfor %}
       </tbody>
</table>

<p>
	<a href="{% url 'grammar:create_dashboard'%}"> <button class="btn btn-primary" value="">Return to Grammar list</button></a>
	<a href="{% url 'grammar:new_question_for_grammar' grammar.id %}"> <button class="btn btn-success" value="">Add a Question</button></a>
</p>
	

{% endblock %}

{% block javascript %}
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover(); 
        $('[data-toggle="tooltip"]').tooltip(); 
    });
{% endblock %}

    

grammar/templates/grammar/gram_create_snippet.html
{% include "main/form_snippet.html" %}
	
	<div class="row">
		<div class="col-md-12">				
			{% for g_concept in uninstantiated_gram_concepts %}
				<span class="button-checkbox">
					<button type="submit" class="btn btn-warning" name="GramConcept" value="{{ g_concept.id }}">
						{{ g_concept.title }}
					</button>
				</span> . 
			{% endfor %}
			{% for g_concept in inst_gram_concepts %}
				<span class="button-checkbox">
					<button type="submit" class="btn btn-success" name="GramConcept" value="{{ g_concept.id }}">
						{{ g_concept.title }}
					</button>
				</span> . 
			{% endfor %}
		</div>
	</div> 

grammar/templates/grammar/gram_list_snippet.html
<table class="table">
{% for counter,type in countlist.items %}
	{% if type == "stage" %}
	<thead class="thead-inverse">
		<tr>
			<th>
				Stage {{ stage_titles|get_item:counter }}
			</th>
		</tr>
	</thead>
	{% elif type == "grammar" %}
	<tr>
		<td><a href="{% url 'grammar:gram_update' grammar_id|get_item:counter %}">{{ grammar_titles|get_item:counter }}</a>({{ grammar_concepts|get_item:counter }})</td>
		<td>
			<a href="{% url 'grammar:gram_update' grammar_id|get_item:counter %}">
				{% if grammar_explanation|get_item:counter %}
					<button type="button" class="btn btn-success" id="grammar_explanation_{{ counter }}">Explanation</button>
				{% else %}
					<button type="button" class="btn btn-warning" id="grammar_explanation_{{ counter }}">Explanation</button>
				{% endif %}		
			</a>	
		</td>
		<td>
			<a href="{% url 'grammar:example_questions' grammar_id|get_item:counter %}">
				{% if grammar_example_question|get_item:counter %}
					<button type="button" class="btn btn-success" id="grammar_example_question_{{ counter }}">Example Question<span class="badge badge-pill badge-success">{{ questions|get_item:counter }}</span></button>
				{% else %}
					<button type="button" 
					{% if questions|get_item:counter == 0 %}
						class="btn btn-danger"
					{% elif questions|get_item:counter < 9 %}
						class="btn btn-warning"					 
					{% else %}
						class="btn btn-success"
					{% endif %}
						id="grammar_example_question_{{ counter }}">Example Question<span class="badge badge-pill badge-success">{{ questions|get_item:counter }}</span></button>
				{% endif %}			
			</a>
		</td>
		<td>
			<form action="{% url 'grammar:grammar_restage' grammar_id|get_item:counter %}" method="post">{% csrf_token %}
				<div class="btn-group">
					<button type="button" id="grammar_restage_{{ counter }}" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Stage<span class="caret"></span>
					</button>
					<ul class="dropdown-menu">
						{% for key,stg in stages.items %}
						
							<li><button type="submit" name="stage" value = "{{ stg.id }}" class="btn-link"> {{ stg.title }}</button></li>
						{% endfor %}
					</ul>
				</div>
			</form>
		</td>
		<td>
			<a href="{% url 'grammar:grammar_delete' grammar_id|get_item:counter %}"><button type="button" class="btn btn-danger"><i class="fas fa-trash" aria-hidden="true"></i></button></a>
 			</td>
 		</tr>
 		{% endif %}
{% endfor %}
</table>

grammar/templates/grammar/gram_update.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    
	{% include "main/form_snippet.html" %}
	<p>
		<a href="{% url 'grammar:create_dashboard'%}"> <button class="btn btn-primary" value="">Return to Grammar list</button></a>
		{% if form.id.value %}
		<a href="{% url 'grammar:new_question_for_grammar' form.id.value %}"> <button class="btn btn-success" value="">Add a Question</button></a>
		{% endif %}		
	</p>
	
{% endblock %}

grammar/templates/grammar/gramconcept_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Create/Update Grammar Concept{% endblock %}

{% block content %}
	
	<form method="POST">
		{% csrf_token%}
		{{ bootstrap_form form }}
		<input type="submit" value="Save" />
	</form>

{% endblock %}

grammar/templates/grammar/gramconcept_list.html
{% extends 'base.html' %}

{% block title %}Grammar Concept List{% endblock %}

{% block content %}

	<ul>

	{% for gramC in object_list %}
	    <li>{{ gramC.title }} 
	    	| <a href="{% url 'grammar:gramconcept_update' gramC.id %}">Update</a>
	    	| <a href="{% url 'grammar:gramconcept_delete' gramC.id %}">Delete</a> 
	    </li>
	{% empty %}
	    <li>No Grammar Concepts found.</li>
	{% endfor %}

	</ul>

<a href="{% url 'grammar:gramconcept_create'%}">Create a new entry</a>

{% endblock %}

grammar/templates/grammar/model_form.html
{% extends 'base.html' %}

{% block title %}Create/Update {{ model_name }}{% endblock %}

{% block content %}
	
{% include "main/form_snippet.html" %}

	<a href="{% url 'grammar:create_dashboard' mode='modelform save'%}">Content Creation Dashboard</a>

{% endblock %}

{% block javascript %}
	// tooltip hover
	$(document).ready(function(){
	    $('[data-toggle="tooltip"]').tooltip();   
	});
{% endblock %}

grammar/templates/grammar/question_ask.html
{% extends 'base.html' %}

{% block title %}Question{% endblock %}

{% block content %}
<div class="card">
	<h3 class="card-header">Grammar Quiz</h3>
	<br>
	<div class="card-block">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Question</h4>
			    <p class="card-text"><i>
			    Translate from 
				{% if question.front.language == question.grammar.target_language %}
					{{ question.target_language }} to {{ question.native_language }}
				{% else %}
					{{ question.native_language }} to {{ question.target_language }}
				{% endif %}	
				</i></p>	
			</div>
			<div class="panel-body">
			    <p><strong>{{ question.front }}</strong></p>
			</div>		
			{% if question.hint != "" %}
				<div class="panel-footer">
					<p><strong>Hint:</strong></p>
				    <p>{{ question.hint|safe }}</p>
				</div>
			{% endif %}
		</div>
		
		<form ajax_url="{% url 'grammar:ajax_submit_answer' %}" method="post" id="ajax-form">
			{% csrf_token %}
			<p>Do your best to answer in the text box provided:</p>				
			<p><input type="text" autofocus name="user_entry" style='width:100%' id="id_user_entry"/></p>
			<input type="hidden" id="question_id" name="question_id" value="{{ question.id }}">
			<br>
			<div class="submitbuttons">
				<input type="submit" id="id_enter_key_submit" style="display:none"/>			
				<input id="id_submitanswer" class="btn btn-primary" type="submit" value="Submit" /><a href="{% url 'grammar:question_score'%}"> <button id="id_pass" type="button" class="btn btn-primary" value="">Pass</button></a>
			</div>
		</form>
		

		<div class="card-block" id="answer">
		</div>	
	<br>
	<table class="table">
		<tr>
			<td style="width: 50%">
				Assessment Progress:
			</td>
			<td style="width: 50%">
				<div class="progress"> 
					<div class="progress-bar progress-bar-info" role="progressbar" style="width: {% widthratio testprogress 1 100 %}%" 
						aria-valuenow="{% widthratio testprogress 1 100 %}" aria-valuemin="0" aria-valuemax="100">
					</div>
				</div>

			</td>
		</tr>
	</table>


	</div>


</div>
{% endblock %}


{% block javascript %}
$('#ajax-form').on('submit', function(event){
    console.log("post_form started");
    if ( !$( "#assess_form_id" ).length ) { 
        // this is before the form has been received an ajax answer
	    event.preventDefault();
	    form = $(this);
	    $('#ajax-form').off('submit');
	    submit_answer(form);    
    };
});

function submit_answer(form) {
	//var question_id = $("#question_id").val();
	console.log("sub_ans started");	
	$.ajax({
		type: "POST",
		url: form.attr("ajax_url"),
		dataType: 'json',
		data: form.serialize(),

		success : function(json) {
		    console.log("success started");
		    $("#id_user_entry").prop("readonly","true"); // prevent the user-entered answer from being altered
		    $("#id_submitanswer").remove();
		    $("#id_pass").remove();
		    //$("#id_enter_key_submit").remove();		    
			//$(".submitbuttons").empty()
		    $("#answer").append(json); // add in new html
		},

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
		    console.log("error started");
            $('#answer').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
	});
};
    
{% endblock %}