coach/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

app_name = 'coach'

urlpatterns = [
    path('tip/create/', views.tip_create_update, name='tip_create'),
    path('tip/update/<int:id>/', views.tip_create_update, name='tip_update'),   
    path('tip/list/', views.tip_list, name='tip_list'),
    path('tip/delete/<int:pk>/', views.TipDelete.as_view(), name='tip_delete'),

    path('tag/create/', views.tag_create_update, name='tag_create'),
    path('tag/update/<int:id>/', views.tag_create_update, name='tag_update'),
    path('tag/list/', views.TagList.as_view(), name='tag_list'),
    path('tag/delete/<int:pk>/', views.TagDelete.as_view(), name='tag_delete'),
]

grammar/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from . import views

app_name = 'grammar'

urlpatterns = [
# add_content views
    path('gramconcept/', views.GramConceptList.as_view(), name='gramconcept_list'),
    path('gramconcept/create/', views.GramConceptCreate.as_view(), name='gramconcept_create'),
    path('gramconcept/update/<int:pk>/', views.GramConceptUpdate.as_view(), name='gramconcept_update'),
    path('gramconcept/delete/<int:pk>/', views.GramConceptDelete.as_view(), name='gramconcept_delete'),
    
    path('grammar/dashboard/', views.create_dashboard, name='create_dashboard'),
    path('grammar/update/<int:pk>/', views.gram_update, name='gram_update'),
    path('grammar/create/', views.gram_update, name='gram_create'),    
    path('grammar/delete/<int:pk>/', views.GrammarDelete.as_view(), name='grammar_delete'),
    path('grammar/restage/<int:pk>/', views.grammar_restage, name='grammar_restage'),
        
    path('question/new_from_grammar/<int:grammar_id>/', views.update_question, name='new_question_for_grammar'),
    path('question/new_from_sentence/<int:sentence_id>/', views.update_question, name='new_question_from_sentence'),
    path('question/new/', views.update_question, name='new_question'),
    path('question/update/<int:question_id>/', views.update_question, name='update_question'),    
    path('question/delete/<int:pk>/', views.QuestionDelete.as_view(), name='question_delete'),
    path('question/list/example_questions/<int:grammar_id>/', views.example_questions, name='example_questions'),

    path('question/ratify/', views.ratify_questions, name='ratify_questions'),
    path('question/view_ratifications/', views.view_ratifications, name='view_ratifications'),
    path('question/apply_ratification_update/<int:pk>/', views.apply_ratification_update, name='apply_ratification_update'),
    
    


# assess views    
    path('assess/initial/', views.initial_grammar_test, name='initial_grammar_test'),
    path('assess/run_initial/', views.run_initial_placement, name='run_initial_placement'),
    path('assess/weekly/schedule_qs/', views.weekly_assessment_schedule_qs, name='weekly_assessment_schedule_qs'),
    path('assess/weekly/ask_qs/', views.weekly_assessment_ask_qs, name='weekly_assessment_ask_qs'),
    path('assess/question_score/', views.question_score, name='question_score'),
    path('ajax/submit_answer/', views.ajax_submit_answer, name='ajax_submit_answer'),
    path('report/', views.weekly_assessment_report, name='weekly_assessment_report'),
]

lang/urls.py
from django.urls import include, path
from django.contrib import admin, admindocs
from lang import views as core_views
from django.conf.urls.i18n import i18n_patterns
from main import views as main_views
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns (
    path('main/', include('main.urls')),
    path('grammar/', include('grammar.urls')),
    path('coach/', include('coach.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),    
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('new_login/', core_views.new_login, name='new_login'),
    path('accounts/logout/', core_views.logout_view, name='logout_view'),
    path('', splash_view, name='splash'),
    path('no_cookies/', no_cookies, name='no_cookies'),
)
"""
django.contrib.auth.urls creates:
    accounts/ login/ [name='login']
    accounts/ logout/ [name='logout']
    accounts/ password_change/ [name='password_change']
    accounts/ password_change/done/ [name='password_change_done']
    accounts/ password_reset/ [name='password_reset']
    accounts/ password_reset/done/ [name='password_reset_done']
    accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
    accounts/ reset/done/ [name='password_reset_complete']
"""    

main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'

urlpatterns = [
    path('test/', views.test, name='test'), 
    path('integrity_check/', views.integrity_check, name='integrity_check'), # run some sort of test - for debugging
    path('', views.switchboard, name='switchboard'),
    path('switchboard/<mode>/', views.switchboard, name='switchboard'),
    path('review_summary/', views.review_summary, name='review_summary'),
                  
    path('select_course/', views.select_course, name='select_course'),
    path('signup_course/', views.signup_course, name='signup_course'),
    path('reset_all_student_progress/', views.reset_all, name='reset_all'),
    path('add_stage/', views.add_stage, name='add_stage'),
    path('getting_started/', views.getting_started, name='getting_started'),
    path('profile/', views.profile_user, name='profile_user'),
    path('register_new_user/', views.register_new_user, name='register_new_user'),
    
]

templates/announcement.html
{% load i18n %}

<div class="jumbotron">
  <p>{% trans "This project is currently in"%}
  <h1>{% trans "Early Beta Release"%}</h1>
  {% comment %}Translators : It is only suitable for testing and feedback purposes. If you would like to be informed when future releases come out, please provide your email address {% endcomment %}
  <p>{% blocktrans %} It is only suitable for testing and feedback purposes. If you would like to be informed when future releases come out, please provide your email address {% endblocktrans %}</p>
  <p><a class="btn btn-primary btn-lg" href="http://eepurl.com/c4Aj2P" role="button">{% trans "Sign up for Announcements"%}</a></p>
  {% comment %}Translators : Announcement Updates{% endcomment %}
  <h3>{% trans "Updates"%}</h3>
  <ul>
    <li>{% blocktrans %}Only English->Turkish currently has content, so please select "English" as one of your native languages during sign-up, and "Learn Turkish" as your course. Otherwise there will be no content to see - sorry!{% endblocktrans %}</li>
  </ul>
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">	
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block head_title %}{% endblock %}</title>
	    <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
		
		{% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" />

		{% bootstrap_javascript jquery='full' %}
		{{ form.media }}
		{% block head %}{% endblock %}
	</head>

	<body>
		{% include 'navbar.html' %}
		<h1><center>{% block title %}{% endblock %}</center></h1>
		<div class="container" id="messages">
			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<div class="alert alert-{% if message.level_tag == 'ERROR' %}danger{% else %}{{ message.level_tag }}{% endif %}">
						    {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
						</div>
					{% endfor %}
				</ul>
			{% endif %}
		</div>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
	    <script type="text/javascript">
		    {% block javascript %}
		    {% endblock %}
	    </script>
	</body>
</html>

templates/field_wrapper.html
<div class="fieldWrapper">
  {{ fld.errors }}
  {% if fld.help_text %}
    <a href="#" data-toggle="tooltip" title="{{ fld.help_text|safe }}">{{ fld.label_tag }}</a>
  {% else %}
  	{{ fld.label_tag }}
  {% endif %}  
  <br>{{ fld }}
</div>

templates/modal_div.html
<!-- Modal -->
{% load i18n %}

<div id="Modal_{{modal_id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">{{ modal_header }}</h4>
      </div>
      <div class="modal-body">
        {{ modal_text|safe }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
        	{% comment %}Translators : Close pop-up window{% endcomment %}
        	{% trans "Close"%}
        </button>
      </div>
    </div>

  </div>
</div>

templates/navbar.html
{% load i18n %}
{% load static %}
{% load bootstrap4 %}

<nav class="navbar navbar-expand-md navbar-light" >
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>

      <a class="navbar-brand" href="{% url 'main:switchboard'%}">      
        <img src="{% static 'images/GFGDlogocolorFSP.svg' %}" style="width:55px;height:55px;"/>
        Grow Fast Grow Deep 
      </a>

    <div class="collapse navbar-collapse" id="navbar1">
          <ul class="navbar-nav">
	          {% if perms.main.content_creator or perms.main.ratify %}
			      <li class="nav-item dropdown">
			          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Administrators</a>
			          <ul class="dropdown-menu">
                            <li class="nav-item active"><a href="{% url 'grammar:ratify_questions'%}">{% trans "Check translations" %}</a></li>			          
			            {% if perms.main.content_creator %}
				            <li class="nav-item"><a href="{% url 'grammar:new_question'%}">{% trans "Questions" %}</a></li>
				            <li class="nav-item"><a href="{% url 'grammar:create_dashboard'%}">{% trans "Grammars" %}</a></li>
				            <li class="nav-item"><a href="{% url 'coach:tip_list'%}">{% trans "Coaching Tips" %}</a></li>
			            {% endif %}
			          </ul>
			      </li>
	          {% endif %}

            <li class="nav-item dropdown">
	          {# Translators : Select Language #}
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{% trans "Language" %}</a>
	          <ul class="dropdown-menu">
		          {% get_available_languages as languages %}
		          {% for language in languages %}
			          <li class="nav-item {% ifequal current_language language.0 %}active{% endifequal %}">
			            <a href="/./{{ language.0}}/accounts/login/?next=" title="{{ language.1 }}">
			              {{ language.1 }}
			            </a>
			          </li>
		          {% endfor %}
	          </ul>
			</li>

	            {% if user.is_authenticated %}
		            <li class="nav-item dropdown">
		              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{% trans "Account" %}</a>
		              <ul class="dropdown-menu">
		                <li><a href="{% url 'main:select_course'%}">{% trans "Change course" %}</a></li>
		                <li role="separator" class="divider"></li>
			            <li><a href="{% url 'logout_view'%}">{% trans "Log out" %}</a></li>
		              </ul>
		            </li>		            
	            {% else %}
                    <li >
                      <a href="{% url 'login'%}" class="nav-link" >{% trans "Log in" %}</a>
                    </li>
                {% endif %}	            
        </ul>
     </div>
     {% if request.session.selected_sp_title %}
        <a href="{% url 'main:select_course'%}">{{ request.session.selected_sp_title }}</a>
     {% endif %}     
</nav>

templates/splash_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}

<style type = "text/css">
    body {
        background-image: url({% static 'images/sunset.jpg' %});
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<br>
<div class="card card-body bg-light" style="background-color:lightblue">
    <img src="{% static 'images/GFGDlogocolorFSP.svg' %}" style="width:255px;height:200px;" align="right"/>
    <br>
    <h3>Free Language coaching tailored for you</h3>
    <a href="{% url 'main:getting_started' %}"><button type="button" class="btn btn-success">Get started</button></a>
    <br>
    
    {% include "announcement.html" %}

    <h2>Serious about learning a language?</h2>
	<p>Grow Fast Grow Deep is the language tool for those serious about reaching fluency.</p>        
	<p>
	You've probably seen language websites making claims like
	</p>
	<blockquote class="blockquote"><p><center>
	<i>Become fluent overnight, without any work, while you sleep...</i>
	</center></p></blockquote>
    <p>
    We won’t pretend genuine fluency doesn’t take hard study. However there is a big difference between study that 
    effectively moves you forward towards fluency and study that produced no discernible results. Grow Fast Grow Deep 
    is the tool for those whose professional life requires genuine fluency in a foreign language.
	</p>
	<p>
	Grow Fast Grow Deep isn’t just a learning tool, it is a coaching tool. It will teach you how to immerse yourself 
	amongst people who speak your target language regardless of whether you are currently living abroad or learning 
	before you travel. Grow Fast Grow Deep will tailor a language learning program to your personal situation walking 
	you though the most effective path to becoming proficient in your target language.
	</p>
	<center>
	<p><i>Learn a language to complete fluency in the most effective manner possible</i></p>
	</center>
</div>
<br><br><br><br><br>
{% endblock %}