lang/urls.py
from django.urls import include, path
from django.contrib import admin, admindocs
from lang import views as core_views
from django.conf.urls.i18n import i18n_patterns
from main import views as main_views
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns (
    path('main/', include('main.urls')),
    path('grammar/', include('grammar.urls')),
    path('coach/', include('coach.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),    
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('new_login/', core_views.new_login, name='new_login'),
    path('accounts/logout/', core_views.logout_view, name='logout_view'),
    path('', splash_view, name='splash'),
    path('no_cookies/', no_cookies, name='no_cookies'),
)
"""
django.contrib.auth.urls creates:
    accounts/ login/ [name='login']
    accounts/ logout/ [name='logout']
    accounts/ password_change/ [name='password_change']
    accounts/ password_change/done/ [name='password_change_done']
    accounts/ password_reset/ [name='password_reset']
    accounts/ password_reset/done/ [name='password_reset_done']
    accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
    accounts/ reset/done/ [name='password_reset_complete']
"""    

main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'

urlpatterns = [
    path('test/', views.test, name='test'), 
    path('integrity_check/', views.integrity_check, name='integrity_check'), # run some sort of test - for debugging
    path('', views.switchboard, name='switchboard'),
    path('switchboard/<mode>/', views.switchboard, name='switchboard'),
    path('review_summary/', views.review_summary, name='review_summary'),
                  
    path('select_course/', views.select_course, name='select_course'),
    path('signup_course/', views.signup_course, name='signup_course'),
    path('reset_all_student_progress/', views.reset_all, name='reset_all'),
    path('add_stage/', views.add_stage, name='add_stage'),
    path('getting_started/', views.getting_started, name='getting_started'),
    path('profile/', views.profile_user, name='profile_user'),
    path('register_new_user/', views.register_new_user, name='register_new_user'),
    
]

main/models/language.py
from django.db import models
from django.contrib.auth.models import User
from common.MixinClasses import TranslatableMixin
import logging

# Languages are used to populate native_language and target_language fields
# Each language has a name, written in the script of that language, and an
# anglicized_name expressing the English name for that language.

class LanguageManager(models.Manager):
    def English(self):
        return Language.objects.get(id=Language.ENGLISH)

class Language(TranslatableMixin, models.Model):
    ENGLISH = 1 # id for English should always be 1
    
    title = models.ForeignKey('main.Sentence', on_delete=models.PROTECT, related_name='LanguageTitle')
    iso693_2 = models.CharField(max_length=8, help_text="Please find the correct code at: https://www.loc.gov/standards/iso639-2/php/code_list.php") 
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = LanguageManager()

    def save(self, *args, **kwargs):
        super(Language, self).save(*args, **kwargs)
        log = logging.getLogger(__name__)
        log.info("Model Language Instance saved:"+str(self))

    class Meta:
        pass

main/views/add_content.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from main.models.stage import Stage
import logging
from .main import mode_completed, mode_not_completed, get_sp_or_redirect

@permission_required('main.add_stage')
def add_stage(request):
    sp,request = get_sp_or_redirect(request)
    if not sp:
        return redirect('main:select_course')

    course = sp.course    
    last_pos = course.stage_set.order_by("position").last().position
    new_stage = Stage.objects.create(position=last_pos+1,course=course,author=request.user)
    log = logging.getLogger(__name__)
    log.info("User" + request.user.username + " added stage "+ str(new_stage))
    return redirect('grammar:create_dashboard')

main/views/assess.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template import Context
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from common import elo, css
from grammar.models import * #GramConcept, Stage, Grammar, Student, StudentProgress, Course, Question, GrammarProgress
from main.models import Stage, Profile
from datetime import date
from django.contrib import messages
import logging
import json
import random
from django.template.loader import render_to_string
from django.http import HttpResponse
from .main import mode_completed, mode_not_completed, get_sp_or_redirect

# many of these views should eventually move into their own dedicated apps

@login_required
def can_do_statements(request):
    log = logging.getLogger(__name__)
    log.info("User" + request.user.username + ": can_do_statements started")

    if request.POST:
        if form.is_valid():
            form.save()
            return mode_completed(request)
    return mode_completed(request)

@login_required
def choose_learning_area(request):
    """ 
    redirects to one of the assessments. 
    when done, redirects to COACHING.
    
    """

    log = logging.getLogger(__name__)
    log.info("User" + request.user.username + ":"+ " choose_learning_area started")

    sp,request = get_sp_or_redirect(request)
    if not sp:
        return redirect('main:select_course')

    # If first call to this routine today...
    if 'assessments_todo' not in request.session:
        if Profile.objects.getval(sp,'initial_grammar_test_completed') is None:
            request.session['assessments_todo'] = 'initial_grammar_test'
        else:
            # For now, each weekly assessment consists only of a weekly grammar test
            request.session['assessments_todo'] = 'weekly_grammar_level' 
    
    # get next_mode by popping it off the list
    request.session['assessments_todo'], next_mode = css.pop(request.session['assessments_todo'])
    if next_mode == '': 
        # assessments finished    
        sp.phase = 'COACHING'    
        sp.mode = ''
    else:
        # cue up next assessment 
        sp.mode = next_mode
    sp.save() 
    return mode_not_completed(request)

@login_required
def listening_comprehension(request):
    log = logging.getLogger(__name__)
    log.info("User" + request.user.username + ": listening_comprehension started")

    if request.POST:
        if form.is_valid():
            form.save()
            return mode_completed(request)
    return mode_completed(request)

@login_required
def reading_comprehension(request):
    log = logging.getLogger(__name__)
    log.info("User" + request.user.username + ": reading_comprehension started")

    if request.POST:
        if form.is_valid():
            form.save()
            return mode_completed(request)
    return mode_completed(request)

@login_required
def vocab_level(request):
    log = logging.getLogger(__name__)
    log.info("User" + request.user.username + ": vocab_level started")

    if request.POST:
        if form.is_valid():
            form.save()
            return mode_completed(request)
    return mode_completed(request)

main/views/homework.py
from .main import mode_completed
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from grammar.views import grammar_progress_table_data
from main.models import Profile
from coach.models import Tip
from django.contrib.auth.decorators import login_required
import logging
from .main import mode_completed, mode_not_completed, get_sp_or_redirect

@login_required
def review_summary(request):
    log = logging.getLogger(__name__)
    log.info("User" + request.user.username + ":"+ __name__ + " review_summary started")
    sp,request = get_sp_or_redirect(request)
    if not sp:
        return redirect('main:select_course')

    if 'checkin_was_today' not in request.session:
        messages.add_message(request, messages.INFO, 'It is too early for your next check-in, but you can review your progress and homework from here at any time.')

    context = {
            'pronunciation_stage':'Not yet measured',   
            'check_in_possible': (sp.new_check_in_valid())
        }
    
    selected_tip_ids = Profile.objects.getval(sp,'selected_tip_ids')
    if selected_tip_ids:
        context.update({'selected_tips':Tip.objects.filter(id__in=selected_tip_ids)})
    selected_exercise_ids = Profile.objects.getval(sp,'selected_exercise_ids')
    if selected_exercise_ids:
        context.update({'selected_exercises':Tip.objects.filter(id__in=selected_exercise_ids)})        
    context.update(grammar_progress_table_data (request))
    return render(request, 'main/review_summary.html', context)

main/views/report.py
from .main import mode_completed
from django.shortcuts import render, redirect, get_object_or_404
import logging
from django import forms
from main.forms import ProfileForm, SignUpForm, CheckInForm
from main.models import Language, Course, StudentProgress, Profile, Student
from coach.models import TipEncounter
from lang.views import logout_view
from .main import mode_completed, mode_not_completed, get_sp_or_redirect, printout_session
from django.contrib.auth import authenticate, login, logout
from datetime import date, timedelta, datetime

def website_induction(request):
    log = logging.getLogger(__name__)
    log.debug("User" + request.user.username + ": website_induction started")

    if request.POST:
        return mode_completed(request)
    context = {'target_language':request.session['target_language']
        }
    
    return render(request, 'main/website_induction.html')

def check_in(request):
    log = logging.getLogger(__name__)
    log.debug("User" + request.user.username + ": check_in started")
    sp,request = get_sp_or_redirect(request)
    if not sp:
        return redirect('main:select_course')

    initial = {'ReportDate': date.today(),    
                'ElapsedDays':sp.days_since_last_checkin(),
                'InputActivities': '<ul><li>Attending class...</li></ul>',
               }
    context = {
        'elapsed_days':sp.days_since_last_checkin(), # days since last check-in
        'last_checkin_date':sp.last_checkin_date(),
        'Weekly_hour_goal':Profile.objects.getval(sp=sp,entry='hour_commitment'),
        }
    if request.POST:
        form = CheckInForm(request.POST, initial=initial)
        if form.is_valid():
            form.save(request)
            # email report to coach if the user has one..
            request.session['checkin_was_today'] = True # Let's review_summary know that this is not a mid-week re-visit
            Profile.objects.create_or_update(sp=sp,entry='last_checkin',text=date.today())            
            return mode_completed(request)
    else:
        form = CheckInForm(None, initial=initial)
    
    # Blank form, or form with errors
    context['form']= form
    return render(request, 'main/check_in.html', context)

# No login required - for anonymous users, however 'profile_data' should be set in session previously
def profile_user(request):
    log = logging.getLogger(__name__)
    log.info("Started profile_user")
    request.session['checkin_was_today'] = True # Let's review_summary know that this is not a mid-week re-visit

    if 'sp_pk' in request.session:
        sp = StudentProgress.objects.get(id=request.session['sp_pk'])
        mode = 'save_to_user'
        log.debug("User " + request.user.username + " view profile_user: sp already exists")        
    else:
        if 'profile_data' not in request.session:
            log.error("profile_data not in request.session when attempting to call view profile_user. redirecting to getting_started")
            printout_session(request)
            return redirect('main:getting_started')
        sp = None
        mode = 'save_to_session'
    
    if request.method == 'POST':
        log.debug("view profile_user: form submitted")        

        form = ProfileForm (request.POST,request=request)
        if form.is_valid():
            log.debug("view profile_user: form valid - saved")
            request = form.save(request=request,mode=mode)
        else:
            log.debug("view profile_user: form invalid - re-rendering")
            return render(request, 'main/profile_new_user.html', {
                'form': form,
            })
    form = ProfileForm (None,request=request)    
    if len(form.fields) > 0:
        log.debug("view profile_user: creating a form and rendering")
        return render(request, 'main/profile_new_user.html', {
            'form': form,
        })            
    else:
        # Profiling done for today
        if sp:
            log.debug("User " + request.user.username + " view profile_user: profile_user all questions done for today, redirecting to switchboard")
            return mode_completed(request)
        else:
            log.debug("view profile_user: profile_user all questions done, redirecting to register_new_user")
            return redirect('main:register_new_user')

def getting_started(request):
    log = logging.getLogger(__name__)
    log.info("starting view getting_started")
    if request.session.test_cookie_worked():
        log.debug("view getting_started: cookies enabled verified")
        request.session.delete_test_cookie()
    else:
        log.info("view getting_started: cookies not enabled, redirecting to splash page with message")
        return redirect('no_cookies')
    if 'sp_pk' in request.session:
        log.debug("User " + request.user.username + " already logged in, view:getting_started redirecting to logout view")
        logout(request)
        return logout_view(request)
    else:
        if 'profile_data' not in request.session:
            request.session['profile_data'] = {}
            log.debug("view:getting_started : request.session.profile_data did not exist, initialised as blank")

        else:
            log.debug("view:getting_started : request.session.profile_data already exists, so not reinitialising")
            printout_session(request)
        return redirect('main:profile_user')

def register_new_user(request):
    log = logging.getLogger(__name__)
    log.debug("Started register_new_user")
    printout_session(request)

    try:
        data = request.session['profile_data']
    except:
        log.error("profile_data not in request.session when attempting to call view register_new_user, redirecting to switchboard")
        printout_session(request)
        return redirect('main:switchboard')
    
    # register a user
    if request.method == 'POST':
        log.debug("register_new_user: processing posted form")
        form = SignUpForm(request.POST)
        if form.is_valid():
            log.debug("register_new_user: creating entries")
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            Student.objects.create(user=request.user,native_languages=data['native_languages'])           
            # create sp for selected course
            if 'course' in data:
                [course_id,native_id] = data['course'].split(',')
                course = get_object_or_404(Course, id=course_id)
                native = get_object_or_404(Language, id=native_id) 
                sp = StudentProgress.objects.create(user=request.user, course=course, native_language=native)
                request.session['sp_pk'] = sp.id
            else:
                log.error("course not in request.session when attempting to call view register_new_user, redirecting to profile_user")
                printout_session(request)
                return redirect('main:profile_user')

            # transfer profile info from session into database                        
            for key in ProfileForm.value_fields:
                if key in data:
                    Profile.objects.create_or_update(sp=sp,entry=key,value=data[key])
                        
            for key in ProfileForm.text_fields:
                if key in data:
                    Profile.objects.create_or_update(sp=sp,entry=key,text=data[key])

            # Record today as last checkin date
            Profile.objects.create_or_update(sp=sp,entry='last_checkin',text=date.today())    
            
            sp.mode = 'register_new_user'
            sp.phase = 'REPORT'
            sp.save()
            return mode_completed(request)
        else:
            log.debug("register_new_user: invalid form")                    
    else:
        log.debug("register_new_user: rendering blank form")        
        form = SignUpForm(None)
    log.debug("register_new_user: rendering signup.html form")        
    return render(request, 'registration/signup.html', {'form': form})

main/templates/main/check_in.html
{% extends 'base.html' %}

{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
{% endblock %}

{% block title %}Weekly Check-in Report{% endblock %}

{% block content %}
<div class="container">
	<p>
		<a href="{% url 'main:review_summary'%}"> <button class="btn btn-primary" value="">Revisit Review Summary</button></a>
	</p>
	<p>It has been {{elapsed_days}} days since your last check-in. Please fill in a log of your language learning activities since your last check-in on {{ last_checkin_date }}.</p>

	<form action="" method="post">{% csrf_token %}
    {% include "main/form_header_snippet.html" %}           
	
		<table>
		   <thead>
		       <tr>
		           <th>Learning category</th>
		           <th>Number of hours</th>
	               <th>What did you do?</th>
		       </tr>
		   </thead>
		   <tbody>
		       <tr width="100%">
		           <td><b>Input</b><br>
	               </td>
	               <td>{{form.InputHours}}</td>
	               <td>{{form.InputActivities}}</td>
	               <td>
	                    <span style="color:Tomato" data-html="true" data-trigger="hover" data-toggle="tooltip" title="Any time deliberate teaching is being done by someone else.<br>Class lessons, sessions with a tutor, Skype lessons, meetings with a language helper in a cafe...">
	                        <i class="fas fa-question-circle fa-lg"></i>
	                    </span>	               
	               </td>
		       </tr>
	           <tr>
	               <td><b>Personal study time</b>
	               </td>
	               <td>{{form.StudyHours}}</td>
	               <td>{{form.StudyActivities}}</td>
	               <td>	               
	                    <span style="color:Tomato" data-html="true" data-trigger="hover" data-toggle="tooltip" title="Any time spent by yourself.<br>Reviewing notes, studying flashcards, reading textbook, watching TV.">
	                        <i class="fas fa-question-circle fa-lg"></i>
	                    </span>	               
	               </td>
	           </tr>
	           <tr>
	               <td><b>Community time</b>
	               </td>
	               <td>{{form.CommunityHours}}</td>
	               <td>{{form.CommunityActivities}}</td>
	               <td>
	                    <span style="color:Tomato" data-html="true" data-trigger="hover" data-toggle="tooltip" title="Any social time spent with native speakers outside a teaching arrangement.<br>Socialising, chatting, visiting a native speaker's home.">
	                        <i class="fas fa-question-circle fa-lg"></i>
	                    </span>
	               </td>
	           </tr>
		   </tbody>	
		</table>
		<p>My total hours: <b><output id="1total_hours">0</output></b></p>
	    <p>Weekly total language hour goal: <b>{{Weekly_hour_goal}}</b>. </p>
	    <p>My weekly hour average is:<b><output id="weekly_avg">0</output></b></p>
	    <p>(<output id="2total_hours">0</output> hours over the past <span id="elapsed">{{elapsed_days}}</span> days)</p>
	    <p>The following factors affected achieving or not achieving my language goal hours during this time:</p>
	    {{form.factors}}
	    <p>I would describe my current level of motivation as...</p>
	    <div class="btn-group" role="group" data-toggle="buttons" aria-label="motivation level">
		    <button type="button" class="btn btn-secondary">    		    
    		    Very low<input hidden name="motivation" aria-hidden="true" value="Very low" type="radio">
		    </button>
            <button type="button" class="btn btn-secondary">                
                Poor<input hidden name="motivation" aria-hidden="true" value="Poor" type="radio">
            </button>
            <button type="button" class="btn btn-secondary">                
                Mediocre<input hidden name="motivation" aria-hidden="true" value="Mediocre" type="radio">
            </button>
            <button type="button" class="btn btn-secondary">                
                Good<input hidden name="motivation" aria-hidden="true" value="Good" type="radio">
            </button>
            <button type="button" class="btn btn-secondary">                
                High<input hidden name="motivation" aria-hidden="true" value="High" type="radio">
            </button>
	    </div>
	    <p>...because: {{form.motivation_reason}}</p>
	    <p>To move forward in my language learning at this time, I need help and advice on the following:</p>
	    {{form.help_request}}
	    <p>Would you like to make an entry this week in the <b>"Embarrassing Language Story Competition"</b>?
            <span style="color:Tomato" data-html="true" data-trigger="hover" data-toggle="popover" title="What is the Embarrasing Language story competition?" 
                data-content="
                <p>The only way to learn a language is by practice and that requires us to make mistakes!</p> 
                <p>If we become ashamed of our mistakes we are likely to stop trying, so research suggests an 
                essential characteristic of successful language students is the ability to laugh at themselves.</p> 
                <p>With that in mind, you are encouraged to 
                revel in your embarrasing language stories. In fact, each week a winner will be selected for the student who 
                has made the most humourous language mistake. Why not share your tears with others and bring them to
                tears of laughter?</p>">  
			    <i class="fas fa-question-circle fa-lg"></i>
			</span>
	       
	    </p>
	    {{form.embarrassing_story}}
	    <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

{% block javascript %}

	$(document).ready(function(){
	    $('[data-toggle="popover"]').popover(); 
        $('[data-toggle="tooltip"]').tooltip(); 
    });

    $('select').change(function(e) { // select element changed
        enableSaveBtn();
    });

    // whenever an hour input is touched, recalc total hours and average
    $("[id$='Hours']").change(function() {
        console.log("activated");
        // sum up hour inputs, by getting their value.
        var hour_total = 
            parseFloat($("[id$='InputHours']").val()) +
            parseFloat($("[id$='StudyHours']").val()) +
            parseFloat($("[id$='CommunityHours']").val());        
		var weekly_avg = hour_total * (7 / ($("#elapsed").html()));
       // store solution in destinations       
       $("[id$='total_hours']").html(Math.round(hour_total));
       $("#weekly_avg").html(Math.round(weekly_avg));       
	});
    
    	
{% endblock %}
            

main/templates/main/continue_button_form_snippet.html
<form method="post" novalidate>
    {% csrf_token %}
    <p>{{ continue_message }}</p>
    <div align="center"><input class="btn btn-primary" autofocus type="submit" value="{{ continue_button_message|default:"Continue" }}" /></div>
</form>

main/templates/main/field_snippet.html
{% load widget_tweaks %}
			  <div class="form-group">
			    {{ field.label_tag }}
			
			    {% if form.is_bound %}
			      {% if field.errors %}
			        {% render_field field class="form-control is-invalid" %}
			        {% for error in field.errors %}
			          <div class="invalid-feedback">
			            {{ error }}
			          </div>
			        {% endfor %}
			      {% else %}
			        {% render_field field class="form-control is-valid" %}
			      {% endif %}
			    {% else %}
			      {% render_field field class="form-control" %}
			    {% endif %}
			
			    {% if field.help_text %}
			      <small class="form-text text-muted">{{ field.help_text }}</small>
			    {% endif %}
			  </div>

main/templates/main/form_header_snippet.html
            {% for hidden_field in form.hidden_fields %}
              {{ hidden_field }}
            {% endfor %}


			{% if form.non_field_errors %}
			  <div class="alert alert-danger" role="alert">
			    {% for error in form.non_field_errors %}
			      {{ error }}
			    {% endfor %}
			  </div>
			{% endif %}

            {% if form.errors %}
              <div class="alert alert-danger" role="alert">
                {{form.errors}}
              </div>
            {% endif %}			

main/templates/main/form_snippet.html
{% load bootstrap4 %}

<form method="post" novalidate>
  {% csrf_token %}

    <div class="panel panel-primary">
		<div class="panel-body">

            {% bootstrap_form form %}
		</div>
	    <div class="panel-footer">
			<div class="row"></div>
			<div class="row">
				<div class="col-md-5"></div>
				<div class="col-md-1">
					<input class="btn btn-primary" type="submit" value="Save" />
			    </div>		
				<div class="col-md-5"></div>
			</div>
		</div>	
    </div>	
</form>

main/templates/main/model_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete {{ model_name }}{% endblock %}

{% block content %}
    <div class="card card-body bg-light">	
	<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
		<input class="btn btn-primary" type="submit" value="Confirm" />

	</form>

{% endblock %}

main/templates/main/model_create.html
{% extends 'base.html' %}

{% block title %}Create {{ model_name }}{% endblock %}

{% block content %}

    {% include "main/form_snippet.html" %}

    <a href="{% url list_url %}"><button type="button" class="btn btn-primary">List of {{ model_name }}</button></a>

{% endblock %}

main/templates/main/model_list.html
{% extends 'base.html' %}

{% block title %}{{ model_name }} List{% endblock %}

{% block content %}
    <table class="table">
        <tbody>
	    	{% for item in object_list %}
		       <tr>
		           <td>
		               <a href="{% url update_url item.id %}"><button type="button" class="btn btn-primary">Update</button></a>    
		           </td>
	               <td>
	                   {{ item.title }}
	               </td>
	               <td>
	                   <a href="{% url delete_url item.id %}"><button type="button" class="btn btn-danger"><i class="fas fa-trash" aria-hidden="true"></i></button></a>
	               </td>
	          </tr>
		   {% empty %}
		   <tr><td>No {{ model_name }}s found.</td></tr>
		   {% endfor %}
        </tbody>
   </table>
    <a href="{% url create_url %}"><button type="button" class="btn btn-success">Create a new {{ model_name }}</button></a>
{% endblock %}

main/templates/main/model_update.html
{% extends 'base.html' %}

{% block title %}{{ model_name }} Update{% endblock %}

{% block content %}

    {% include "main/form_snippet.html" %}
    <a href="{% url create_url %}"><button type="button" class="btn btn-success">Create a new {{ model_name }}</button></a>
    <a href="{% url list_url %}"><button type="button" class="btn btn-primary">List of {{ model_name }}</button></a>

{% endblock %}

main/templates/main/profile_new_user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<font color="black">Welcome! Tell us a little about yourself</font>{% endblock %}

{% block content %}

	<div class="card card-body bg-light">
		<style type = "text/css">
		    body {
		        background-image: url({% static 'images/village.jpg' %});
		        background-size: cover;
		        background-repeat: no-repeat;
		    }
		</style>



        {% include "main/form_snippet.html" %}
	</div>
{% endblock %}

main/templates/main/select_course.html
{% extends 'base.html' %}

{% block title %}{{ form_title }}{% endblock %}

{% block content %}

   
	<div class="card card-body bg-light">
		<form action="" method="post" id="signup_form">
			{% csrf_token %}
			<table class="table">
				<tbody>				
				{% for record in course_details %}
					<tr>
    					<td>
							{% if record.course_health > record.course.QUALITY.MEDIUM.value %}
							    <label class="btn btn-success">Course quality {{record.course.QUALITY.MEDIUM.description}}
							{% elif record.course_health > record.course.QUALITY.LOW.value %}
							    <label class="btn btn-warning">Course quality {{record.course.QUALITY.LOW.description}}
							{% else %}
							    <label class="btn btn-danger">Course still in development
							{% endif %}
                            <input type="radio" style="display: none;" name="selection_code" id="course_radio{{ forloop.counter }}" value="{{ record.course_code }}" />
                            
                            </label>
                        </td>
                        <td>
                            {{ record.course_title }}
                        </td>
					</tr>
                {% empty %}
                    <tr><td>There are no other courses available</td></tr>					
				{% endfor %}
				</tbody>
			</table>
		</form>
	</div>
	{% if add_signup_option %}
        <a href="{% url "main:signup_course" %}">Sign up for a new course</a>
    {% endif %}
{% endblock %}

{% block javascript %}
    $('input[id^=course_radio]:radio').change(function() {
        console.log("radios other clicked");
        $('#signup_form').submit();
    });
{% endblock %}

main/templates/main/test.html
{% extends 'base.html' %}

{% block title %}Test completed{% endblock %}

{% block content %}
    
    test done!
{% endblock %}


{% block javascript %}

{% endblock %}